name: Stackpack Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile/Test/Package
      run: |
        [ -z "${ARTIFACTORY_USERNAME}" ] && echo "username doesnt exist"
        [ -z "${ARTIFACTORY_PASSWORD}" ] && echo "pwd doesnt exist"
        [ -z "${TIZIANO_TEST}" ] && echo "tiziano doesnt exist"
        sbt compile test package
